# Generated by Django 5.2.1 on 2026-08-02 07:41

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingmedia_softwarepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarepackage',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='listings/packages/'),
        ),
    ]
